### ISSUE TITLE
Mail alway send to info@cases.lu ?

### ISSUE THREAD

**Issue by Foxi352** [CASES-LU/MonarcAppFO#10]
Did i do something wrong or is here a configuration step missing in your readme ?

When a user tries to use the "Mot de passe oublié ?" it always sends the emails to info@cases.lu instead of the email address the user entered.

```
2017-06-16 15:08:13 1dLqyw-00008N-Ib => info@cases.lu R=smarthost T=remote_smtp_smarthost H=******* [xxx.xxx.xxx.xxx] X=TLS1.2:ECDHE_RSA_AES_256_CBC_SHA384:256 CV=no DN="CN=*****" C="250 2.6.0 <E1dLqyw-00008N-Ib@******> [InternalId=76982993813521, Hostname=********] 3260 bytes in 0.102, 31,063 KB/sec Queued mail for delivery"
2017-06-16 15:08:13 1dLqyw-00008N-Ib Completed

```

**Comment by cedricbonhomme** [comment]
Do you still have have this issue?

**Comment by Foxi352** [comment]
Yes.

To reproduce go to "Mot de passe oublié ?", enter email address of a known account and hit <Return> or click on "Réinitialiser [....]" and you'll see outgoing mail to info@cases.lu instead of the entered account email address.

```
2017-06-22 07:59:52 1dNv9k-00054Q-Pz <= <> R=1dNv9h-00054P-5q U=Debian-exim P=local S=1856
2017-06-22 07:59:55 1dNv9k-00054Q-Pz => info@cases.lu R=smarthost T=remote_smtp_smarthost H=srvexchange.****.lu [*******] X=TLS1.2:ECDHE_RSA_AES_256_CBC_SHA384:256 CV=no DN="CN=srvexchange.******" C="250 2.6.0 <E1dNv9k-00054Q-Pz@srvmonarc.*****.lu> [InternalId=77571404333060, Hostname=*******] 3288 bytes in 0.100, 32,076 KB/sec Queued mail for delivery"
2017-06-22 07:59:55 1dNv9k-00054Q-Pz Completed
```

**Comment by adulau** [comment]
@cedricbonhomme  Could this be related to?

https://github.com/CASES-LU/zm-core/blob/3d705c15e09616db761a3affbcacc7e6b88731c5/config/module.config.php#L506

**Comment by cedricbonhomme** [comment]
I do not think. It seems to be related to the FROM field (https://github.com/CASES-LU/zm-core/blob/3ad42425d06d860b30e868a003a2d15d005217df/src/MonarcCore/Service/MailService.php#L38). Anyway, when I change this value on my VM, this changes nothing...

It seems that the TO field is simply set here:
https://github.com/CASES-LU/zm-core/blob/b7de99eb0b0960d53d5b27720d9b0e4feca6b883/src/MonarcCore/Service/PasswordService.php#L97

The thing is that it is working on my VM (generated with Vagrant), without any configuration

```ini
Jun 22 07:27:57 ubuntu-zesty postfix/pickup[1646]: E1A9A7D84F: uid=33 from=<info@cases.lu>
Jun 22 07:27:57 ubuntu-zesty postfix/cleanup[2365]: E1A9A7D84F: message-id=<20170622072757.E1A9A7D84F@ubuntu-zesty>
Jun 22 07:27:57 ubuntu-zesty postfix/qmgr[1647]: E1A9A7D84F: from=<info@cases.lu>, size=1127, nrcpt=1 (queue active)
Jun 22 07:28:01 ubuntu-zesty postfix/smtp[2369]: E1A9A7D84F: to=<username@domain.com>, relay=mx.domain.com[.....]:25, delay=3.7, delays=0.05/0.01/2/1.6, dsn=2.0.0, status=sent (250 bjTy1v02J06C5H901 mail accepted for delivery)
Jun 22 07:28:01 ubuntu-zesty postfix/qmgr[1647]: E1A9A7D84F: removed
```

**Comment by Foxi352** [comment]
I use exim on Debian Jessie. I'll try to also launch your Vagrant build and check if it works. And if it does i'll try to replace exim by postfix, also this should not be change anything, but who knows...

**Comment by cedricbonhomme** [comment]
yes, I would be surprised if this "solve" the problem.

**Comment by Foxi352** [comment]
This is strange. I installed postfix in your vagrant box and it worked.
I then uninstalled exim4 from my prod server and replaced it by Postfix -> et voilà is works ...

Although i was able to send mails from bash via exim without any problems ...

So this issue can be closed, at least for me. Maybe you could do yourself some tests with exim to see if you can reproduce.

**Comment by cedricbonhomme** [comment]
thank you for this precision.

We need to investigate why this is not working with exim4. This is really weird.
