### ISSUE TITLE
AbstractService: Move the risk calculations methods into a separate helper class

### ISSUE THREAD

**Issue by xplodwild** [CASES-LU/MonarcAppFO#2]
In [AbstractService.php around line 677 to 733](https://github.com/CASES-LU/zm-core/blob/53a62022489d152e4cb53a4d3c2234d1048e907b/src/MonarcCore/Service/AbstractService.php#L677-L733), the risk calculation methods are directly put as methods.

This doesn't make sense as they are used only in a limited set of services, and should be moved into a separate (helper) class as static methods, as they don't require a specific state nor a specific entity.

**Comment by dealmeida** [comment]
Create a trait for risks calculation methods
