### ISSUE TITLE
AbstractService: Replace mcrypt_encrypt/decrypt calls with their openssl counterparts

### ISSUE THREAD

**Issue by xplodwild** [CASES-LU/MonarcAppFO#3]
In [AbstractService.php around line 677 to 733](https://github.com/CASES-LU/zm-core/blob/53a62022489d152e4cb53a4d3c2234d1048e907b/src/MonarcCore/Service/AbstractService.php#L883-L905), the methods mcrypt_encrypt and mcrypt_decrypt are deprecated.

The mcrypt PHP module is deprecated as of PHP 7.1 and will be removed in PHP 7.2. See the [PHP 7.1 deprecation article](http://php.net/manual/fr/migration71.deprecated.php) for more information. The mcrypt library has been in an abandoned state for over a decade, and thus might present security issues in the future.

It is advised to use the OpenSSL equivalent, `openssl_encrypt` and `openssl_decrypt`.

**Comment by eurodude** [comment]
This is an interesting task as the chosen algorithm is not mappable to openssl algortithm (MCRYPT_RIJNDAEL_256). So all the data exported will not be compatible with the new version. 

However, importing in the old version of a file, then upgrading MONARC, then exporting again should work fine to "port" the files.

**Comment by eurodude** [comment]
The issue has been resolved
